services:
  db:
    image: docker.iranserver.com/library/mariadb:10.5
    env_file: env.ini
    volumes:
      - ./data:/docker-entrypoint-initdb.d:Z
    

  wp:
    #image: docker.iranserver.com/library/wordpress:php8.2-apache
    build:
      context: .
      dockerfile: Containerfile
    env_file: env.ini
    depends_on: 
      - db
    ports:
      - 8484:80
    volumes:
      - ./public_html:/var/www/html:Z

  adminer:
    image: docker.iranserver.com/library/adminer:4.6
    ports:
      - 8686:8080
volumes:
  wpsite: {}

